#冒号后必须加空格
#-后必须加空格，这是列表写法
#键: 值这是字典写法，冒号后也要加空格
#布尔值推荐小写
model:
  name: hh
  pretrained: true

train:
  epoch: 50
  lr: 0.001
  batch_sieze: 32
  option:
    - 1
    - 2
    - [111, 222]
    - |
      111
      222

